
replicaCount: 1

image:
  repository: hello-world
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}
# Pod-level securityContext applied to `spec.securityContext`.
# Setting a seccompProfile at the pod level helps satisfy PodSecurity "restricted".
podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

# Container-level securityContext applied to each container. The PodSecurity
# policy requires allowPrivilegeEscalation=false and a seccompProfile set on
# the container or pod.
securityContext:
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault
#  capabilities:
#    drop:
#      - ALL
#  readOnlyRootFilesystem: true
#  runAsNonRoot: true
#  runAsUser: 1000
#  capabilities:
#    drop:
#      - ALL
#  readOnlyRootFilesystem: true
#  runAsNonRoot: true
#  runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
